on:
  workflow_call:
    inputs:
      words:
        required: true
        type: string
jobs:
  a-test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.words }}
      shell: bash



