name: action test
on:
    push:
        branches: [ main ]
jobs:
    a-test:
        runs-on: ubuntu-latest
        steps:
            - name: test
              uses: ./.github/workflows/test/my_action
              with:
                words: "just a test"