name: action test
on:
    push:
        branches: [ main ]
jobs:
    a-test:
        runs-on: ubuntu-latest
        steps:

            - name: check out repository
              uses: actions/checkout@v3

            - name: test
              uses: team-317/try-github-workflow/.github/workflows/test
              with:
                words: "just a test"
