name: action test
on:
    push:
        branches: [ main ]
jobs:
    a-test:
        runs-on: ubuntu-latest
        steps:
            - name: check out repository
              uses: actions/checkout@v3

    reuse-job:
        uses: team-317/try-github-workflow/.github/workflows/test/action.yml@main
        with:
            words: "just a test"
